### ISSUE TITLE
Use int as datatype for your slot machine grid?

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#1]
https://github.com/CapioIM/P5SlotMachine/blob/4f14d18bc61f2a21734e2168af1208bdabc0f584/P5SlotMachine/Program.cs#L10-L11

https://github.com/CapioIM/P5SlotMachine/blob/4f14d18bc61f2a21734e2168af1208bdabc0f584/P5SlotMachine/Program.cs#L28-L29

Currently you are using a string array for captions and a two dimensional string array for your slot machine itself. 
Just use an two dimensional int array!
And instead of reading out the captions from the array, only fill the slotMachineArray with the generated numbers. Makes it much easier?

Or what will be the special handling for your "J" in the slotSymbols?

**Comment by CapioIM** [comment]
if letters will be used , it seems that char or string will be more suitable
