### ISSUE TITLE
DIAGONAL_LINES_IN_GAME wrong start value

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#11]
https://github.com/CapioIM/P5SlotMachine/blob/3bdf8a19393b3d681f98bc545dcb1bc0ebf49597/P5SlotMachine/Program.cs#L168

I think you used the wrong constant here as start value DIAGONAL_LINES_IN_GAME

And in fact, you can make this second diagonal check work with only one loop variable too, if you start the loop again at 0 like the loop for first diagonal.

The calculation for the columnIndex can be done with the loop variable then too, as there is a pattern. 
First diagonal cell will be [0,2] then [1,1] and [2,0] do you see the pattern?

**Comment by mayisa87** [comment]
[07:38, 22.9.2023] Isabella Mayer: You don't need a nested loop. What I meant was, first of all, that you use DIAGONAL_LINES_IN_GAME instead of DIAGONAL_LINE_LENGTH
[07:46, 22.9.2023] Isabella Mayer: And what I meant about "starting at 0", if you start this for loop at 0, up to <DIAGONAL_LENGTH you could work with the loop variable to calculate the positions to be accessed without having and adttional diagonalRow variable

So like in the example, the first value to be accessed is [0,2]
0 -> you get from your counter/loop variable
2 -> can be calculated from DIAGONAL_LENGTH and loop variable

**Comment by mayisa87** [comment]
I just checked on the latest version of code, cool that you accumulated all into one loop :) 

What needs to be still changed, don't use magic numbers, so you have here 0 and 2 and whatever, like this lines

https://github.com/CapioIM/P5SlotMachine/blob/261abead263dc08946191f6e84b0ff571cb37607/P5SlotMachine/Program.cs#L124
https://github.com/CapioIM/P5SlotMachine/blob/261abead263dc08946191f6e84b0ff571cb37607/P5SlotMachine/Program.cs#L126

You could use DIAGONAL_LINE_LENGTH-1, so it is generic and if you later on would change the length of lines, your code will still work.
https://github.com/CapioIM/P5SlotMachine/blob/261abead263dc08946191f6e84b0ff571cb37607/P5SlotMachine/Program.cs#L136-140

But beside this, I think you can close this issue then :) Really good work!!!

**Comment by CapioIM** [comment]
done, forgot to comment fix in commit
