### ISSUE TITLE
Make your constants public, or move to logic class

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#15]
https://github.com/CapioIM/P5SlotMachine/blob/2587cc517bdb0cd9d4cf169c0c750133915e3617/P5SlotMachine/LogicMethods.cs#L35C60-L35C60

In general it is of course OK, to use constants and give it as parameter to your method. But you should always think about, if

- the constant is maybe only used in the logic and should be better moved to the other class. So if a constant is only used in LogicMethods and never in Program.cs, move it.
- If the constant is often used in other parts of the code, move it out of the static Main method in Program.cs, before the method and make it public. like `public const int COLUMN_LINES_IN_GAME = 3;`
- or another option in larger applications can be, to move all constants to a separated file like Constants.cs and define it public in there, so you can access the constants in your code where ever you want.

If you choose one of this options, you can remove it as parameter in your method ;)

**Comment by CapioIM** [comment]
thanks , done
