### ISSUE TITLE
Naming of methods

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#16]
https://github.com/CapioIM/P5SlotMachine/blob/2587cc517bdb0cd9d4cf169c0c750133915e3617/P5SlotMachine/LogicMethods.cs#L35

In C# the method name must start with uppercase letter and should be made of a verb or a couple: verb + noun. The name is formatted by following the Upper Camel Case convention (PascalCase), i.e. each word, including the first one, starts with uppercase.

https://csharp-book.softuni.org/Content/Chapter-10-methods/method-naming/method-naming.html

        public static int RowArrayLoop(int[,] array, int HowManyColumnsInArray, int rowLinesPlayCounter)

So instead of RowArrayLoop it should be something like GetHorizontalMatchCount or GetHorizontalLineMatches etc.

**Comment by CapioIM** [comment]
thanks , got it
