### ISSUE TITLE
Naming of loop variables

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#17]
https://github.com/CapioIM/P5SlotMachine/blob/2587cc517bdb0cd9d4cf169c0c750133915e3617/P5SlotMachine/LogicMethods.cs#L38
https://github.com/CapioIM/P5SlotMachine/blob/2587cc517bdb0cd9d4cf169c0c750133915e3617/P5SlotMachine/LogicMethods.cs#L42

I don't know if we did not mention this before, but you can name your loop variables what ever you want. So instead of always using i and j for loop variables, you can name it for example rowIndex and colIndex. This makes it much easier for other people to understand your code.

See here a short video Florian did.
https://www.loom.com/share/e4c281111fbf46a78b97bf493b2e4a8a

**Comment by CapioIM** [comment]
yes you did, at the start of Slot Machine Project
