### ISSUE TITLE
Do separate display logic from filling with values

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#18]
https://github.com/CapioIM/P5SlotMachine/blob/e08b86328c80d2fbdcf45545973f9a5d97fd0fde/P5SlotMachine/LogicMethods.cs#L68

Currently you fill and display the slot machine at the same time. Always try to separate such things. So Write one method to fill the array, and return the new array as return type. So do not give it as parameter, but return a new array as return value :)

And then, have a separate method, that only displays the grid.

It is better to have this separated, so you can call the display metod from other places in code too if you would need it, independently from the filling with values.

**Comment by CapioIM** [comment]
many methods have calculations and display of these

**Comment by CapioIM** [comment]
Done and Done
