### ISSUE TITLE
Use a constant for the max number to be filled in array

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#19]
https://github.com/CapioIM/P5SlotMachine/blob/e08b86328c80d2fbdcf45545973f9a5d97fd0fde/P5SlotMachine/LogicMethods.cs#L74

Use a constant to define the maximum number to be set in array. So you really only want to show 0 or 1 to user? Nice for the user as the possibility to win is higher ;)

**Comment by CapioIM** [comment]
depending on time even with these odds it might be impossible to win, happened once

**Comment by mayisa87** [comment]
OK, but anyway, define a constant for the maximum number to be filled into array ;) So like MAX_GRID_VALUE = 1, so you can use it in your random number generation

**Comment by mayisa87** [comment]
Sorry for all the updates ;) Code was not updated on the laptop so I thought this issue wasn't finished yet ;) 

Concerning constants, and usage in the .Next() cal of the random generator. If you want to generate numbers from 0 to 9, your MAX_SLOT_NUMBER_OPTIONS should be defined with 9 and not 10. 

You should always assign the value right. Not storing 10 to the constant, only to make the random generator call working.
Imagine you would need somewhere else the information of maximum value filled into the grid, 10 wouldn't be the right value at all. 

So better store 9 to the constant and change your call to: `Random.Next(0,MAX_SLOT_NUMBER_OPTIONS+1);`

**Comment by CapioIM** [comment]
indeed , that's easier
