### ISSUE TITLE
Define enums always at the beginning of class or in separated file

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#21]
https://github.com/CapioIM/P5SlotMachine/blob/e08b86328c80d2fbdcf45545973f9a5d97fd0fde/P5SlotMachine/LogicMethods.cs#L158-L165

Enums should be always define at the beginning of a class or even in a separated file. All defintions, fields, enums, properties (you will come to that soon in next Module) have to be defined at the start, this is a general coding convention to easily look up things. :)

**Comment by CapioIM** [comment]
yeah, I found myself searching for them at some point
