### ISSUE TITLE
Use simple type cast to get the value of enum

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#22]
https://github.com/CapioIM/P5SlotMachine/blob/e08b86328c80d2fbdcf45545973f9a5d97fd0fde/P5SlotMachine/LogicMethods.cs#L135

Enums, especially if you use it for simple int or char, are so comfortable to use, as you can get a value just by a type cast. 

So you can assign values to your enums and then just cast it to int:
```
 public enum RowOrColumn
  {
      Rows = 0,
      Columns = 1,
  }
```

In Code you can use it like this, where the (int) part is the type cast. So compiler automatically converts the given enum to an int.

result += GetAndDisplayWinLine(check, slotMachineArray, RowIndex, **(int)**RowOrColumn.Columns);

So you can get rid of the GetLengthRowOrColumn method :)

**Comment by CapioIM** [comment]
thanks for explaining, if I am not making 1 loop to check vertical or horizontal lines , I don't think ill need it :)
