### ISSUE TITLE
Remove and Sort Usings

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#24]
https://github.com/CapioIM/P5SlotMachine/blob/50e311f45bb10e4d5c076005782ea5a1a9eeebcc/P5SlotMachine/UIMethods.cs#L2

Often automatically this usings are added to code.  Before pushing code always have a look and remove them. You can right click on them and choose "Remove and Sort Usings"

**Comment by CapioIM** [comment]
will do that in future, I thought that they are necessary there for Program.cs to ....work
