### ISSUE TITLE
Method to return the maximum of lines to play

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#25]
https://github.com/CapioIM/P5SlotMachine/blob/518961fd4642124d013163ebfcd9a1f7b651a4d9/P5SlotMachine/LogicMethods.cs#L32

As you use it in your UI too, you could implement a very simple method like "GetAmountAllLines" or "GetMaxLinesToPlay" that just returns the sum of your constants. So you can use it where you need it, and the benefit of such small help methods is, that you can easily change it later on to return a different value :)

**Comment by CapioIM** [comment]
I've been thinking about it, I think
