### ISSUE TITLE
Overloading of method

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#27]
https://github.com/CapioIM/P5SlotMachine/blob/bb1fca5a7495333ea313a326e2ba70d5f9b6072e/P5SlotMachine/UIMethods.cs#L14-L21

I see that you overloaded the GetNumberFromPlayer. In general, overloading is a cool option. Smart one :) But in this case, you only give the enum as parameter, as you already now in your Program.cs when calling the method, that the user should/will now input the number of lines to play.

So as the message given to the overloaded method is only there to differ if the user now enters the lines to play, it is better to do a separat method.
Overloading makes sense, if there is really a separated logic. So if you would have a different handling for all messages given to method for example. ANd usually then, when overloading, you call the original method like GetNumberFromUser and then work with the result and do the special logic then. 

So there would be a different solution, that suits better here.

Instead of overloading, write a new method in UIMethods GetNumberOfLinesFromUser without parameters.

Inside you call the already existing GetNumberFromUser() that returns the integer. And then, you can do your if and check if the given integer is greater than the lines to play.

**Comment by CapioIM** [comment]
I was thinking to do different method, both number of lines and bet ask for same thing with only difference that amount of lines is not above 8, where bet can be above.

**Comment by mayisa87** [comment]
You implemented the new method, cool!

But as written above, you could simplifiy it if you implementbit like:
```
```

int result = GetNumbersFromPlayer(); 
if (result > LogicMethods.GetMaxPlayableLines())
                    {
                        result = LogicMethods.GetMaxPlayableLines();
                    }
                    return Math.Abs(result);
```
