### ISSUE TITLE
Why do the amount of rows and columns differ?

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/P5SlotMachine#6]
https://github.com/CapioIM/P5SlotMachine/blob/4f14d18bc61f2a21734e2168af1208bdabc0f584/P5SlotMachine/Program.cs#L6-L7

Why is it that you got 3 columns but 4 rows? The description requires a 3x3 grid?

Maybe add more details about your version of the game to the readme file!

**Comment by CapioIM** [comment]
just checking if code scales without issues

**Comment by mayisa87** [comment]
If you just do this for testing, please commit and push with the final data, not with test data. As it confuses other team mates or in your cause, us coaches ;)
